GR/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('order.urls'))
]

order/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

# just for test
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^inprocess/(?P<cookie>(.*))/$', views.in_process, name='in_process'),
    url(r'^restaurants/$', views.restaurant_list, name='restaurant_list'),
    url(r'^restaurants/(?P<restaurant_pk>[0-9]+)/$', views.group_menu, name = 'group_menu'),
    url(r'^restaurants/(?P<restaurant_pk>[0-9]+)/startorder/$', views.start_order, name = 'start_order'),
    url(r'^restaurants/(?P<restaurant_pk>[0-9]+)/(?P<order_pk>[0-9]+)/$', views.in_order, name = 'in_order'),
    url(r'^restaurants/(?P<restaurant_pk>[0-9]+)/(?P<order_pk>[0-9]+)/(?P<user>[A-Z,a-z,0-9]+)/$', views.individual_menu, name = 'individual_menu'),
    url(r'^endorder/(?P<order_pk>[0-9]+)/$', views.end_order, name = 'end_order'),
    url(r'^orderlist/$', views.order_list, name='order_list'),
    url(r'^error/(?P<info>(.*))/$', views.error, name = 'error'),
    url(r'^logout/$', views.logout, name = 'logout')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
# coding=utf-8

from django.db import models
import os
import json

logo_path = 'logo/'
dish_path = 'dish/'
default_image = 'default.jpg'
max_length = 100

# Create your models here.
class People(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=max_length)
    money_left = models.FloatField()
    def __str__(self):
        return str(self.email)

class Timestamp(models.Model):
    usage = models.CharField(max_length=max_length)
    timestamp = models.DateTimeField()
    def __str__(self):
        return str(self.usage)

class Status(models.Model):
    usage = models.CharField(max_length=max_length)
    status = models.BooleanField()
    def __str__(self):
        return str(self.usage)

class Restaurant(models.Model):
    identifier = models.CharField(max_length=max_length)
    name = models.CharField(max_length=max_length)
    status = models.BooleanField()
    logo  = models.ImageField('Logo', upload_to=logo_path, default=default_image)
    arrival = models.IntegerField()
    sales = models.IntegerField()
    deliver_cost = models.FloatField()
    minimum_expense = models.FloatField()
    rate = models.FloatField()
    name_for_url = models.CharField(max_length=max_length)
    def __str__(self):
        return self.name

class Dish(models.Model):
    restaurant = models.ForeignKey(Restaurant)
    group = models.CharField(max_length=max_length)
    rating = models.FloatField()
    tips = models.TextField()
    month_sales = models.IntegerField()
    rating_count = models.IntegerField()
    food_id = models.CharField(max_length=max_length)
    name = models.CharField(max_length=max_length)
    price = models.FloatField()
    image  = models.ImageField('Menu', upload_to=dish_path, default=default_image)
    def __str__(self):
        return '{0} {1}'.format(self.name, str(self.price))

class OrderList(models.Model):
    restaurant = models.ForeignKey(Restaurant)
    timestamp = models.DateTimeField()
    is_submitted = models.BooleanField()
    def __str__(self):
        return '{0} {1}'.format(self.restaurant.name, str(self.timestamp))

class Order(models.Model):
    order_list = models.ForeignKey(OrderList)
    customer = models.ForeignKey(People)
    dishes = models.ManyToManyField(Dish)
    #def __setattr__(self, key, value):
        #super(Order, self)._setattr__(key, value)
        #self.__dict__[key] = value
        #if key in ['order_list']:
            #self.dishes = Dish.objects.filter(restaurant = self.order_list.restaurant)

    def __str__(self):
        return self.customer.name

order/forms.py
# coding=utf-8

from django import forms
from django.utils import timezone
from .models import Order, OrderList, Restaurant

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('order_list', 'customer')

    dishes = forms.ModelMultipleChoiceField(queryset = None, widget=forms.CheckboxSelectMultiple())

    def __init__(self, order_list, customer, *args, **kwargs):
        initial = {
           'order_list': order_list,
           'customer': customer,
          }
        if 'initial' in kwargs.keys():
            kwargs['initial'].update(initial)
        else:
            kwargs['initial'] = initial
        # Initializing form only after you have set initial dict
        super(forms.ModelForm, self).__init__(*args, **kwargs)

        self.fields['dishes'].queryset = order_list.restaurant.dish_set.all()
        self.fields['order_list'].widget = forms.HiddenInput()
        self.fields['customer'].widget = forms.HiddenInput()

order/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import OrderForm
from .mail import send_order_mail
from .helpers import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from spider.spider.login import *

is_in_ordering_usage = "is_in_ordering"
is_email_sent_usage = "is_email_sent"

# Create your views here.
def login(request):
    cookie = get_captcha()
    return render(request, 'order/login.html', {'cookie' : cookie})

def logout(request):
    system_logout(request)
    return redirect('login')

def in_process(request, cookie):
    username = request.POST['Username']
    pw = request.POST['Password']
    captcha = request.POST['Captcha']
    login_info = web_login(username, pw, captcha, cookie)
    if login_info['success']:
        if system_login(request):
            return redirect('restaurant_list')
    return redirect('error', 'Failed to login')

def restaurant_list(request):
    if not request.user.is_authenticated():
        return redirect('error', 'Not authenticated')

    lastest_order = get_latest_order_list()

    #pull data everyday on 9:00
    #if should_refresh_data():
        #refresh_nearby_restaurants()

    paginator = Paginator(Restaurant.objects.all(), 10) # Show 5 restaurants per page
    page = request.GET.get('page')
    try:
        restaurants = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        restaurants = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        restaurants = paginator.page(paginator.num_pages)
    return  render(request, 'order/restaurant_list.html', {'restaurants' : restaurants, 'lastest_order':lastest_order})

def order_list(request):
    lastest_order = get_latest_order_list()
    order_lists = OrderList.objects.all().order_by('-timestamp')
    return render(request, 'order/order_list.html', {'lastest_order':lastest_order, 'order_lists' : order_lists})

def group_menu(request, restaurant_pk):
    if not request.user.is_authenticated():
        return redirect('error', 'Not authenticated')

    is_in_ordering = get_status(is_in_ordering_usage)
    restaurant = Restaurant.objects.get(pk = restaurant_pk)
    if is_in_ordering:
        order_list = get_latest_order_list()
        if order_list != None:
            return redirect('in_order', restaurant_pk=order_list.restaurant.pk, order_pk=order_list.pk)
        else:
            return redirect('error', 'Wrong status')
    else:
        refresh_dish_in_restaurant(restaurant)
        dishes = build_dishes_in_group(restaurant)
        return render(request, 'order/group_menu.html', {'dishes':dishes, 'restaurant':restaurant})

def start_order(request, restaurant_pk):
    if not request.user.is_authenticated():
        return redirect('error', 'Not authenticated')

    restaurant = Restaurant.objects.get(pk = restaurant_pk)
    order_list = setup_order_list(restaurant)
    set_status(is_in_ordering_usage, True)
    #redirect to in_order page
    return redirect('in_order', restaurant_pk=restaurant_pk, order_pk=order_list.pk)

def individual_menu(request, restaurant_pk, order_pk, user):
    order_list = OrderList.objects.get(pk = order_pk)
    customer = People.objects.get(name=user)
    form = OrderForm(order_list, customer)
    dishes = build_dishes_in_group(order_list.restaurant)
    try:
        order = order_list.order_set.get(customer=customer)
    except Order.DoesNotExist:
        order = None
    selected_dishes = []
    if order != None:
        selected_dishes += order.dishes.all()
    return render(request, 'order/individual_menu.html', {'customer' : customer, 'form' : form, 'order_list' : order_list, 'dishes' : dishes, 'selected_dishes':selected_dishes})

def in_order(request, restaurant_pk, order_pk):
    order_list = OrderList.objects.get(pk = order_pk)
    latest_order_list = get_latest_order_list()
    is_ordering = get_status(is_in_ordering_usage)
    is_current_order_list = (order_list == latest_order_list)
    #do nothing if the order list is already out-of-date
    if is_current_order_list:
        if request.method == 'POST' and not order_list.is_submitted:
            update_customer_order(order_list, request)
        if not get_status(is_email_sent_usage) and not order_list.is_submitted:
            send_order_mail(request.build_absolute_uri())
            set_status(is_email_sent_usage, True)
    return render(request, 'order/in_order.html', {'order_list' : order_list, 'is_ordering' : is_ordering, 'is_current_order_list' : is_current_order_list})

def end_order(request, order_pk):
    if not request.user.is_authenticated():
        return redirect('error', 'Not authenticated')

    set_status(is_in_ordering_usage, False)
    set_status(is_email_sent_usage, False)
    order_list = OrderList.objects.get(pk = order_pk)
    order_list.is_submitted = True
    order_list.save()
    deduct_expense_from_people(order_list)
    return render(request, 'order/end_order.html', {'order_list' : order_list})

def error(request, info):
    set_status(is_in_ordering_usage, False)
    set_status(is_email_sent_usage, False)
    return render(request, 'order/error.html', {'info' : info})

order/templates/order/end_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{order_list.restaurant.name}}</title>
    {% load filters %}
</head>
<body>
<div class="nav-bar" style="width: 100%; position: fixed; margin-top: 0px;z-index: 9999; background-color: white">
<div class="row" style="font-size: 19px; background-color: #ddffdd">
    {% if request.user.is_authenticated %}
        <div class="col-md-2"><a href="{% url 'logout' %}">{{ request.user.username }} logout</a></div>
        <div class="col-md-1"><a href="{% url 'restaurant_list' %}">返回首页</a></div>
    {% endif %}

</div>
<div>
    <h3>
        {{order_list.restaurant.name}} 订单已提交
    </h3>
</div>
<div>
    共消费 ￥{{ order_list|total_consumption_per_order_list }}
    <br>外送费 ￥{{ order_list.restaurant.deliver_cost }}
</div>
</div>
<div style="width: 100%; padding-top: 150px; z-index: 10000">
    <table>
        {% for order in order_list.order_set.all %}
            <tr>
                <td>{{ order.customer.name }} ￥{{ order.dishes.all|total_consumption_per_order }}:</td>
                {% for dish in order.dishes.all %}
                    <td style="padding-left:60px">{{ dish }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>

order/templates/order/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
<div class="row" style="font-size: 19px; background-color: #ddffdd">
    {% if request.user.is_authenticated %}
        <div class="col-md-2"><a href="{% url 'logout' %}">{{ request.user.username }} logout</a></div>
    {% endif %}
    <div class="col-md-1"><a href="{% if request.user.is_authenticated %}
                                       {% url 'restaurant_list' %}
                                   {% else %}
                                       {% url 'login' %}
                                   {% endif %}">
                         返回首页</a></div>
</div>
<h1>{{ info }}</h1>
</body>
</html>

order/templates/order/group_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <meta charset="UTF-8">
    <title>{{restaurant.name}}</title>
    {% load filters %}
</head>
<body>
<div class="nav-bar" style="width: 100%; position: fixed; margin-top: 0px;z-index: 9999; background-color: white">
    <div>
        <h3>
            <b>{{restaurant.name}}</b>
            <a class="btn btn-default" href="{% url 'start_order' restaurant_pk=restaurant.pk %}"><span class="glyphicon glyphicon-pencil">start order</span></a>
        </h3>
    </div>
    <div class="row" style="font-size: 19px; background-color: #ddffdd">
        {% if request.user.is_authenticated %}
            <div class="col-md-2"><a href="{% url 'logout' %}">{{ request.user.username }} logout</a></div>
        {% endif %}
        <div class="col-md-1"><a href="{% url 'restaurant_list' %}">返回首页</a></div>
    </div>
</div>
    <div class="container-fluid" style="width: 100%; padding-top: 120px; z-index: 10000">
        <div class="row" style="font-size: 14px">
        {% for group_name in dishes.keys %}
            <div class="row">
                <div class="col-md-12"><br></div>
            </div>
            <div class="row">
                <div class="col-md-12" style="font-size: 26px"><b>{{ group_name }}</b></div>
            </div>
            {% for dish in dishes|find_dishes_by_group:group_name%}
            <div class="col-md-2" style="height: 180px">
                <img src= "{{ dish.image.url }}" height="80" width="80">
                <br>{{ dish.name }}
                <br>{{ dish.rating }}分 ({{ dish.rating_count }}评)
                  月售{{ dish.month_sales }}份
                <br>{{ dish.price }}元
            </div>
            {% endfor %}
        {% endfor %}
        </div>
    </div>
</body>
</html>

order/templates/order/in_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <meta charset="UTF-8">
    <title>{{ order_list.restaurant.name }}</title>
    {% load filters %}
</head>
<body>
<div class="nav-bar" style="width: 100%; position: fixed; margin-top: 0px;z-index: 9999; background-color: white">
{% if request.user.is_authenticated %}
<div class="row" style="font-size: 19px; background-color: #ddffdd">
    {% if request.user.is_authenticated %}
        <div class="col-md-2"><a href="{% url 'logout' %}">{{ request.user.username }} logout</a></div>
    {% endif %}
    <div class="col-md-1"><a href="{% url 'restaurant_list' %}">返回首页</a></div>
</div>
{% endif %}
<div><br></div>
{% if not order_list.is_submitted and is_current_order_list and request.user.is_authenticated%}
<div>
    <a class="btn btn-default" href="{% url 'end_order' order_pk=order_list.pk %}"><span class="glyphicon glyphicon-pencil">end order</span></a>
</div>
{% endif %}
<div>
    {% if order_list.is_submitted %}
        <h1>
            此订单已提交
        </h1>
    {% else %}
        {% if is_current_order_list %}
            <h1>
                正在点餐中...
            </h1>
        {% else %}
            <h1>
                此订单已过期
            </h1>
        {% endif %}
    {% endif %}
</div>
<div>
    <h3>
        {{order_list.restaurant.name}} 点单情况
    </h3>
</div>
<div>
    共消费 ￥{{ order_list|total_consumption_per_order_list }}
    <br>外送费 ￥{{ order_list.restaurant.deliver_cost }}
</div>
</div>
<div style="width: 100%; padding-top: 280px; z-index: 10000">
    <table>
        {% for order in order_list.order_set.all %}
            <tr>
                <td>{{ order.customer.name }} ￥{{ order.dishes.all|total_consumption_per_order }}:</td>
                {% for dish in order.dishes.all %}
                    <td style="padding-left:60px">{{ dish }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>

order/templates/order/in_process.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录中</title>
</head>
<body>
<h1>登录中...</h1>
</body>
</html>

order/templates/order/individual_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load filters %}
    {% load staticfiles %}
    <script type="text/javascript" src="/static/jquery-1.11.3.js"></script>
    <script charset="UTF-8">
        function display_consumption()
        {
            money_left = {{ customer.money_left }} - total_consumption;
            document.getElementById('total_consumption').innerHTML = "total consumption: ￥" + total_consumption + "<br>moeny left: ￥" + money_left;
        }

        function remove_dish(p_id, checkbox_id, dish_price)
        {
            $('#'+p_id).remove();
            $('#'+checkbox_id).removeAttr('checked');
            total_consumption -= dish_price;
            display_consumption();
        }
        var total_consumption = 0;
        var money_left = 0;
        function select_dish(dish, dish_pk, dish_price){
            var p_id = "selected_dish_" + dish_pk;
            var checkbox_id = "id_dishes_" + dish_pk;
            var remove_button_id = "remove_dish_" + dish_pk;
            if(document.getElementById(checkbox_id).checked)
            {
                total_consumption += dish_price;
                var p = document.createElement("p");
                p.setAttribute("id", p_id);
                $(p).text(dish);
                var remove_button = document.createElement("button");
                remove_button.setAttribute("id", remove_button_id);
                remove_button.setAttribute("type", "button");
                remove_button.setAttribute("style", "margin-left:10px");
                remove_button.innerHTML = "-";
                remove_button.onclick = function(){remove_dish(p_id, checkbox_id, dish_price)};
                $(p).append(remove_button);
                $('#user_choices').append(p);
            }
            else
            {
                total_consumption -= dish_price;
                $('#'+p_id).remove();
            }

            display_consumption();
        }
    </script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <meta charset="UTF-8">
    <title>Welcome {{ customer.name }}</title>
</head>
<body>
<div class="nav-bar" style="width: 100%; position: fixed; margin-top: 0px;z-index: 9999; background-color: white">
<div class="row" style="font-size: 19px; background-color: #ddffdd">
    {% if request.user.is_authenticated %}
        <div class="col-md-2"><a href="{% url 'logout' %}">{{ request.user.username }} logout</a></div>
    {% endif %}
    <div class="col-md-5"><a href="{% url 'in_order' restaurant_pk=order_list.restaurant.pk order_pk=order_list.pk%}">点单情况</a></div>
</div>
<div>
    <h2><b>{{ order_list.restaurant.name }}</b></h2>
</div>
</div>
<div style="width: 100%; padding-top: 80px; z-index: 10000">
{% if order_list.is_submitted %}
    <h4>此订单已提交</h4>
{% else %}
    <form action="{% url 'in_order' restaurant_pk=order_list.restaurant.pk order_pk=order_list.pk %}" method="POST">
        {% csrf_token %}
        <input id="id_customer" name="customer" type="hidden" value="{{ customer.pk }}">
        <input id="id_order_list" name="order_list" type="hidden" value="{{ order_list.pk }}">
        <div class="container-fluid" style="width: 100%; height: 100%; overflow: auto;">
        <div class="row" style="font-size: 14px; width: 70%; height: 100%; float: left;">
        {% for group_name in dishes.keys %}
            <div class="row">
                <div class="col-md-12"><br></div>
            </div>
            <div class="row">
                <div class="col-md-12" style="font-size: 26px"><b>{{ group_name }}</b></div>
            </div>
            {% for dish in dishes|find_dishes_by_group:group_name%}
            <div class="col-md-4" style="height: 180px">
                <label for="id_dishes_{{ dish.pk }}">
                    <input class="dish_checkbox" type="checkbox" name="dishes"
                           id="id_dishes_{{ dish.pk }}" value="{{ dish.pk }}"
                            {% if dish in selected_dishes %} checked {% endif %}
                           onchange="javascript:select_dish('{{ dish }}', {{ dish.pk }}, {{ dish.price }});"/>
                </label>
                <img src= "{{ dish.image.url }}" height="80" width="80">
                <br>{{ dish.name }}
                <br>{{ dish.rating }}分 ({{ dish.rating_count }}评)
                  月售{{ dish.month_sales }}份
                <br>{{ dish.price }}元
            </div>
            {% endfor %}
        {% endfor %}
        </div>
        <div id="user_choices" style="position: fixed; top: 110px; margin-left: 70%;float: right; height: 100vh; width: 30%; background-color: #aaaaaa">
            <p id="total_consumption">
                total consumption: ￥0
                <br>money left: ￥{{ customer.money_left }}
            </p>
            <div><input class="submit_choices" type="submit" value="Submit Order" /></div>
        </div>
        </div>
    </form>
{% endif %}
</div>

    <script>
        $(document).ready(document_ready());
        function document_ready()
        {
            load_selected_dish();
        }

        function load_selected_dish()
        {
            {% for dish in selected_dishes %}
                select_dish('{{ dish }}', {{ dish.pk }}, {{ dish.price }});
            {% endfor %}

            //$(":checkbox:checked").each(function () {
            //     var dish_pk = $(this).attr("value");
            //     select_dish('unknown', dish_pk, 0);
            // });

            //var checkboxes = document.getElementsByClassName('dish_checkbox');
            //for(var i = 0; i < checkboxes.length; i++)
            //{
            //    if(checkboxes[i].checked)
            //    {
            //        var dish_pk = checkboxes[i].value;
            //    }
            //}

        }
    </script>
</body>
</html>

order/templates/order/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BMW Group Ordering</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>
<h1 style="text-align: center"><b>BMW Group Ordering</b></h1>
{% if request.user.is_authenticated %}
    <div class="row" style="font-size: 19px; background-color: #ddffdd">
        <div class="col-md-2"><a href="{% url 'logout' %}">{{ request.user.username }} logout</a></div>
        <div class="col-md-1"><a href="{% url 'restaurant_list' %}">返回首页</a></div>
    </div>
    <h1>已登陆</h1>
{% else %}
<form action='{% url 'in_process' cookie=cookie %}' method='POST'> {% csrf_token %}
    <div class="container">
        <p>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-1"><label for='username'> Username </label></div>
            <div class="col-md-2"><input type='text' name='Username' id='username'></div>
        </div>
        </p>
        <p>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-1"><label for='password'>Password </label></div>
            <div class="col-md-2"><input type='password' name='Password' id='password'></div>
        </div>
        </p>
        <p>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-1"><label for='captcha'>Captcha </label></div>
            <div class="col-md-2"><input type='captcha' name='Captcha' id='captcha'></div>
            <img src= "../media/captcha.jpg">
        </div>
        </p>
        <p style="text-align: center"><input type='submit' value='login'></p>
        <p style="text-align: center; color: red">
            Notice: The account for lunch order organizer should be registered
            <br>both on ELEME server and BMW Group Ordering system!
        </p>
    </div>
</form>
{% endif %}
</body>
</html>

order/templates/order/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order history</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="nav-bar" style="width: 100%; position: fixed; margin-top: 0px;z-index: 9999; background-color: white">
<div>
    <h1 style="text-align: center" ><b>BMW Group Ordering</b></h1>
</div>
<div class="row" style="font-size: 19px; background-color: #ddffdd">
    <div class="col-md-1"></div>
    {% if request.user.is_authenticated %}
        <div class="col-md-2"><a href="{% url 'logout' %}">{{ request.user.username }} logout</a></div>
        <div class="col-md-1"><a href="{% url 'restaurant_list' %}">首页</a></div>
    {% endif %}
    <div class="col-md-1"><a href="{% if lastest_order != None %}
                                      {% url 'in_order' restaurant_pk=lastest_order.restaurant.pk order_pk=lastest_order.pk%}
                                   {% else %}
                                      {% url 'error' info='No order history'%}
                                   {% endif %}">
                                   本次订单</a></div>
</div>
</div>
<div style="width: 100%; padding-top: 120px; z-index: 10000">
    {% for order in order_lists %}
        <div class="row" style="font-size: 19px">
            <div class="col-md-5"><a href="{% url 'in_order' restaurant_pk=order.restaurant.pk order_pk=order.pk%}">{{ order }}</a></div>
            {% if not order.is_submitted %}
                <div class="col-md-1" style="color: red">未提交</div>
            {% endif %}
        </div>
    {% endfor %}
</div>
</body>
</html>

order/templates/order/start_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>start order</title>
</head>
<body>

</body>
</html>